### ISSUE TITLE
Contao 5

### ISSUE THREAD

**Issue by jedoCodes** [markocupic/contao-php2xliff#1]
Contao 5 requires "codefog/contao-haste" in version 5+ 

`
"codefog/contao-haste": "^4.20 || ^5.0"
`

and a litte error after fix the contao-haste version

` Declaration of Markocupic\ContaoPhp2Xliff\DependencyInjection\MarkocupicContaoPhp2XliffExtension::getAlias() must be compatible with Symfony\Component\DependencyInjection\Extension\Extension::getAlias(): string`

this can fixed by added ": string" to your "MarkocupicContaoPhp2XliffExtension::getAlias()" function

**Comment by markocupic** [comment]
Fixed in version 1.1.0
https://github.com/markocupic/contao-php2xliff/commit/14cb456b8eaa92af00a94d8f014833da444d9f53
